### PR TITLE
fix double count of active jurors

### LINKED ISSUE #12: activeJuror in parent courts counting twice
If a juror stakes in a court and in some parent court (for example, non-technical and general court), the activeJuror in the general court will be summed twice because there is no check.

### LINKED ISSUE #18: fix double count on unstake
Similar to https://github.com/salgozino/kleros-subgraph/pull/13

1) juror stakes in court A
2) juror stakes in court B (subcourt of A)
3) if juror unstakes from A, `CourtA.activeJurors` should not change because he's still staked in B

### PR DESCRIPTION
**Pull request by rodsouto**

### CODE REVIEW

File: tests/src/mocks.ts [hunk 1]
```diff
@@ -245,18 +245,101 @@ export class KlerosLiquid {
     static bind(contract: Address) {
         return {
             courts: (id: BigInt2) => {
+                const courtsConfig = {
+                    0: {
+                        parent: new BigInt2(0),
```
Comment (salgozino) [inline tests/src/mocks.ts:250]: The court 0 hasn't a parent court in the graph.
In the SC has the court 0 as parent. Method 8 in the [kleros liquid smart contract](https://etherscan.io/address/0x988b3a538b618c7a603e1c11ab82cd16dbe28069#readContract)

what should be the correct behavior?

Comment (rodsouto) [reply tests/src/mocks.ts:250]: It's working ok because of this check https://github.com/salgozino/kleros-subgraph/blob/master/src/KlerosLiquidMappings.ts#L482 , so the court 0 ends with parent=null instead of parent=0

**Comment by rodsouto** [comment]
Green everywhere! @salgozino ready for review :D

image
